site_name: Project Documentation Template
site_description: Comprehensive documentation template for technical projects
site_author: Development Team
site_url: https://your-org.github.io/your-project

# Repository information
repo_name: your-project
repo_url: https://github.com/your-org/your-project
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Development Team

# Configuration
theme:
  name: material
  language: en
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/git-alt

# Plugins
plugins:
  - search:
      lang: en
  # Git revision tracking:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      timezone: UTC
      locale: en
      fallback_to_build_date: true
  - git-committers:
      repository: your-org/your-project
      branch: main
      token: !ENV [MKDOCS_GIT_COMMITTERS_APIKEY, GITHUB_TOKEN]
  # Optional plugins (disabled temporarily):
  # - mermaid2:
  #     version: 10.4.0
  # - minify:
  #     minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Components: components.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
  - Architecture:
    - System Design: architecture/system-design.md
    - Security Model: architecture/security-model.md
  - User Guide:
    - Basic Operations: user-guide/basic-operations.md
    - Advanced Configuration: user-guide/advanced-configuration.md
  - Use Cases:
    - Overview: use-cases/overview.md
    - Use Case 1: use-cases/use-case-1.md
    - Use Case 2: use-cases/use-case-2.md
    - Use Case 3: use-cases/use-case-3.md
  - Development:
    - Development Setup: development/development-setup.md
    - Testing Guide: development/testing-guide.md
    - Quality Assurance: development/quality-assurance.md
    - Release Management: development/release-management.md
  - Configuration:
    - Basic Configuration: configuration/basic-config.md
    - Advanced Settings: configuration/advanced-settings.md
    - Security Configuration: configuration/security.md
  - API Reference:
    - API Overview: api/overview.md
    - Endpoints: api/endpoints.md
    - Authentication: api/authentication.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - Debugging Guide: troubleshooting/debugging.md

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css

# Custom JavaScript - now handled by mermaid2 plugin
# extra_javascript:
#   - assets/javascripts/mermaid.js

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/your-project
  version:
    provider: mike
